### ISSUE TITLE
install on linux?

### ISSUE THREAD

**Issue by jole78** [mjbvz/vscode-styled-components-extension#1]
Hey,

great initiative on bundling this as an extension. 
A question though...how do I install it? It's not on market place right?

I'm on linux so vsix is not doable I think.

Again...thanks!

**Comment by mjbvz** [comment]
Yes this is currently not published to the marketplace because it depends on experimental functionality and the extension itself is not where I'd like it to be yet.

You should be able to install it from the vsix in this repo  though, even on Linux. Have you tried these steps: https://code.visualstudio.com/docs/editor/extension-gallery#_install-from-a-vsix

**Comment by jole78** [comment]
@mjbvz hey I didn't know that was possible...great. However, got this error...dunnow why?
```

Error: end of central directory record signature not found
    at /usr/share/code/resources/app/node_modules/yauzl/index.js:183:14
    at /usr/share/code/resources/app/node_modules/yauzl/index.js:618:5
    at /usr/share/code/resources/app/node_modules/fd-slicer/index.js:32:7
    at FSReqWrap.wrapper [as oncomplete] (fs.js:629:17)
```
**update:** never mind...my bad. I just downloaded the vsix file (of course I needed the whole repo...downloaded the zip and unzipped it and ran the vsix from there...works)

**Comment by jole78** [comment]
...and it works!! and works in sub-directories to...this is "way better" and the preferred way I would say to handle it...via an extension. Great work!
